name: Cypress Automated Tests on Develop
on:
  schedule:
    - cron: '15 22 * * 1-5'

jobs:
  cypress-run:
    name: Running Automated Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
